from importlib.metadata import version
from pathlib import Path

import pytest
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name


def _major_minor(distribution: str) -> tuple[int, int]:
    major, minor, *_rest = version(distribution).split(".")
    return int(major), int(minor)


def _top_level_requirements(path: Path) -> list[Requirement]:
    requirements: list[Requirement] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        if raw_line[:1].isspace():
            continue
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        requirements.append(Requirement(line))
    return requirements


def _normalized_requirement_names(path: Path) -> set[str]:
    return {
        canonicalize_name(requirement.name)
        for requirement in _top_level_requirements(path)
    }


def _assert_distribution_absent(path: Path, distribution: str) -> None:
    assert canonicalize_name(distribution) not in _normalized_requirement_names(path)


def _requirements_by_name(path: Path) -> dict[str, list[Requirement]]:
    by_name: dict[str, list[Requirement]] = {}
    for requirement in _top_level_requirements(path):
        name = canonicalize_name(requirement.name)
        by_name.setdefault(name, []).append(requirement)
    return by_name


def test_langgraph_stack_uses_approved_minor_lines() -> None:
    assert _major_minor("langgraph") == (1, 2)
    assert _major_minor("langchain") == (1, 3)
    assert _major_minor("langgraph-checkpoint-sqlite") == (3, 1)
    assert _major_minor("langchain-deepseek") == (1, 1)


@pytest.mark.parametrize("relative", ("requirements.txt", "requirements-lock.txt"))
def test_anthropic_sdk_is_absent_from_direct_and_resolved_requirements(
    relative: str,
) -> None:
    _assert_distribution_absent(Path(relative), "anthropic")


def test_anthropic_gate_rejects_normalized_direct_requirement_mutation(
    tmp_path: Path,
) -> None:
    mutated = tmp_path / "requirements.txt"
    mutated.write_text("Anthropic[bedrock]==999.0.0\n", encoding="utf-8")

    old_predicate = not any(
        line.strip().startswith("anthropic")
        for line in mutated.read_text(encoding="utf-8").splitlines()
    )
    assert old_predicate is True
    with pytest.raises(AssertionError):
        _assert_distribution_absent(mutated, "anthropic")


def test_anthropic_gate_rejects_resolved_lock_mutation(tmp_path: Path) -> None:
    mutated = tmp_path / "requirements-lock.txt"
    mutated.write_text(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile requirements.txt --universal "
        "--python-version 3.12 -o requirements-lock.txt\n"
        "pydantic==2.13.4\n"
        "anthropic==999.0.0\n",
        encoding="utf-8",
    )

    command = " ".join(mutated.read_text(encoding="utf-8").splitlines()[:3])
    assert "--universal" in command
    assert "--python-version 3.12" in command
    with pytest.raises(AssertionError):
        _assert_distribution_absent(mutated, "anthropic")


def test_lock_is_generated_for_python_312_across_supported_platforms() -> None:
    lock_path = Path("requirements-lock.txt")
    header = lock_path.read_text(encoding="utf-8").splitlines()[:3]
    command = " ".join(header)
    assert "--universal" in command
    assert "--python-version 3.12" in command

    by_name = _requirements_by_name(lock_path)
    assert any(
        str(requirement.marker) == 'sys_platform == "win32"'
        for requirement in by_name["colorama"]
    )
    assert any(
        str(requirement.marker) == 'sys_platform == "linux"'
        for requirement in by_name["triton"]
    )
